dist: trusty
language: node_js
sudo: required
node_js:
  - '7'
services:
  - docker
  - mongodb
env:
  - NODE_ENV="test"
before_script:
  - npm install
script:
  - npm test
after_script:
 # For dev branch
 - |
     if [ "$TRAVIS_BRANCH" == "dev" ]; then
       docker build -t compiax/platypus-api:dev-latest .
       docker tag compiax/platypus-api:dev-latest compiax/platypus-api:dev-latest
       docker login -u $DOCKER_USER -p $DOCKER_PASS
       docker push compiax/platypus-api:dev-latest
     fi

 # For master branch
 - |
     if [ "$TRAVIS_BRANCH" == "master" ]; then
       docker build -t compiax/platypus-api:latest .
       docker tag compiax/platypus-api:latest compiax/platypus-api:latest
       docker login -u $DOCKER_USER -p $DOCKER_PASS
       docker push compiax/platypus-api:latest
     fi
